<h1 style="color:blue;text-align:center">Model Serialization & Deserialization using <code style="color:red"> pickle</code> module.</h1>

In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
df = pd.DataFrame({'area':np.array([300,200,500,100,700]),'price':np.array([2000,1500,3000,1900,4000])})

In [4]:
df

area  price
0   300   2000
1   200   1500
2   500   3000
3   100   1900
4   700   4000

In [5]:
from sklearn.linear_model import LinearRegression


In [6]:
lr = LinearRegression()
lr.fit(df[['area']],df['price'])

LinearRegression()

In [17]:
lr.score(df[['area']],df['price'])

0.8997120840748077

In [7]:
lr.predict([[250]])

/home/jrana/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2040.94827586])

save model as serialize object in a file

In [8]:
with open('model_pickle','wb') as f:
    pickle.dump(lr,f)

In [9]:
with open('model_pickle','rb') as f:
    model=pickle.load(f)

In [10]:
model.predict([[250]])

/home/jrana/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2040.94827586])

<h1 style="color:blue;text-align:center">Model Serialization & Deserialization using <code style="color:red"> joblib</code> module.</h1>

In [12]:
import joblib

In [13]:
joblib.dump(lr,'model_joblib')

['model_joblib']

In [14]:
model=joblib.load('model_joblib')

In [15]:
model.predict([[250]])

/home/jrana/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2040.94827586])

**Joblib** or **Pickle**

joblib is faster in saving/loading large NumPy arrays, whereas pickle is faster with large collections of Python objects. Therefore, if your model contains large NumPy arrays (as the majority of models does), joblib should be faster.